### ISSUE TITLE
deadlock when sending and detaching at the same time

### ISSUE THREAD

**Issue by devigned** [vcabbage/amqp#119]
When sending while the session is detaching, the sender can enter into a deadlock state. Below is the `kill -SIGABRT $pid` output from one of my test runs.

```
goroutine 0 [idle]:
runtime.futex(0xd3b548, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffec754d548, 0x41098b, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:530 +0x21
runtime.futexsleep(0xd3b548, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:45 +0x4b
runtime.notesleep(0xd3b548)
	/usr/local/go/src/runtime/lock_futex.go:151 +0x9b
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1952 +0xe5
runtime.findrunnable(0xc42002c500, 0x0)
	/usr/local/go/src/runtime/proc.go:2415 +0x50c
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2541 +0x13b
runtime.park_m(0xc4201dbe00)
	/usr/local/go/src/runtime/proc.go:2604 +0xb6
runtime.mcall(0x148)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x5b

goroutine 1 [select, 1299 minutes]:
github.com/devigned/testhub/cmd.glob..func6(0xd33c00, 0xc42019a000, 0x0, 0x5)
	/go/src/github.com/devigned/testhub/cmd/max_send.go:145 +0x53a
github.com/devigned/testhub/vendor/github.com/spf13/cobra.(*Command).execute(0xd33c00, 0xc4200a6020, 0x5, 0x5, 0xd33c00, 0xc4200a6020)
	/go/src/github.com/devigned/testhub/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/devigned/testhub/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xd340c0, 0xd58440, 0xc4200969c0, 0x9ea96a)
	/go/src/github.com/devigned/testhub/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/devigned/testhub/vendor/github.com/spf13/cobra.(*Command).Execute(0xd340c0, 0xc420061e48, 0x4848bd)
	/go/src/github.com/devigned/testhub/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/devigned/testhub/cmd.Execute()
	/go/src/github.com/devigned/testhub/cmd/root.go:37 +0x2d
main.main()
	/go/src/github.com/devigned/testhub/main.go:45 +0x69

goroutine 19 [syscall, 2444 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 37 [select, 1299 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*Sender).send(0xc42030c440, 0xa56e00, 0xc42029c1b0, 0xc42015aee0, 0x0, 0x0, 0x0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:410 +0x49a
github.com/devigned/testhub/vendor/pack.ag/amqp.(*Sender).Send(0xc42030c440, 0xa56e00, 0xc42029c1b0, 0xc42015aee0, 0xc420456240, 0xa5c3a0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:337 +0x6a
github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go.(*sender).trySend(0xc42058c900, 0xa56e00, 0xc42029c1b0, 0xa55880, 0xc420912080, 0x0, 0x0)
	/go/src/github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go/sender.go:129 +0x23a
github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go.(*sender).Send(0xc42058c900, 0xa56e00, 0xc42029c150, 0xc420912080, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go/sender.go:111 +0x18e
github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go.(*Hub).SendBatch(0xc420402000, 0xa56e00, 0xc42029c0f0, 0xc420912040, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go/hub.go:559 +0x19d
github.com/devigned/testhub/cmd.(*repeatSender).Run(0xc42032fb40, 0xa56d40, 0xc42006c1c0, 0xc4202b1920, 0xc4202b18c0)
	/go/src/github.com/devigned/testhub/cmd/max_send.go:87 +0x389
created by github.com/devigned/testhub/cmd.glob..func6
	/go/src/github.com/devigned/testhub/cmd/max_send.go:136 +0x285

goroutine 38 [select, 1336 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*Sender).send(0xc42062e000, 0xa56e00, 0xc420194300, 0xc42015a000, 0x0, 0x0, 0x0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:410 +0x49a
github.com/devigned/testhub/vendor/pack.ag/amqp.(*Sender).Send(0xc42062e000, 0xa56e00, 0xc420194300, 0xc42015a000, 0xc420428180, 0xa5c3a0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:337 +0x6a
github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go.(*sender).trySend(0xc4205ad080, 0xa56e00, 0xc420194300, 0xa55880, 0xc4200a5c40, 0x0, 0x0)
	/go/src/github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go/sender.go:129 +0x23a
github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go.(*sender).Send(0xc4205ad080, 0xa56e00, 0xc4201942d0, 0xc4200a5c40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go/sender.go:111 +0x18e
github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go.(*Hub).SendBatch(0xc420070120, 0xa56e00, 0xc420194270, 0xc4200a5c00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go/hub.go:559 +0x19d
github.com/devigned/testhub/cmd.(*repeatSender).Run(0xc42032fb80, 0xa56d40, 0xc42006c1c0, 0xc4202b1920, 0xc4202b18c0)
	/go/src/github.com/devigned/testhub/cmd/max_send.go:87 +0x389
created by github.com/devigned/testhub/cmd.glob..func6
	/go/src/github.com/devigned/testhub/cmd/max_send.go:136 +0x285

goroutine 39 [select, 2434 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*Sender).send(0xc4200a4080, 0xa56e00, 0xc420202120, 0xc42040c000, 0x0, 0x0, 0x0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:410 +0x49a
github.com/devigned/testhub/vendor/pack.ag/amqp.(*Sender).Send(0xc4200a4080, 0xa56e00, 0xc420202120, 0xc42040c000, 0xc4203b01a0, 0xa5c3a0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:337 +0x6a
github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go.(*sender).trySend(0xc42052aa40, 0xa56e00, 0xc420202120, 0xa55880, 0xc42030cec0, 0x0, 0x0)
	/go/src/github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go/sender.go:129 +0x23a
github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go.(*sender).Send(0xc42052aa40, 0xa56e00, 0xc4202020f0, 0xc42030cec0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go/sender.go:111 +0x18e
github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go.(*Hub).SendBatch(0xc420132a80, 0xa56e00, 0xc420202030, 0xc42030ce40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/devigned/testhub/vendor/github.com/Azure/azure-event-hubs-go/hub.go:559 +0x19d
github.com/devigned/testhub/cmd.(*repeatSender).Run(0xc42032fbc0, 0xa56d40, 0xc42006c1c0, 0xc4202b1920, 0xc4202b18c0)
	/go/src/github.com/devigned/testhub/cmd/max_send.go:87 +0x389
created by github.com/devigned/testhub/cmd.glob..func6
	/go/src/github.com/devigned/testhub/cmd/max_send.go:136 +0x285

goroutine 40 [select, 2444 minutes, locked to thread]:
runtime.gopark(0xa0fe70, 0x0, 0x9ea630, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc4201eb750, 0xc42019e420)
	/usr/local/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1

goroutine 2724 [select, 1299 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*conn).connReader(0xc4200bb0e0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/conn.go:529 +0x32c
created by github.com/devigned/testhub/vendor/pack.ag/amqp.(*conn).start
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/conn.go:245 +0x43

goroutine 2585 [select, 1336 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*conn).connReader(0xc4201a85a0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/conn.go:529 +0x32c
created by github.com/devigned/testhub/vendor/pack.ag/amqp.(*conn).start
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/conn.go:245 +0x43

goroutine 2715 [select, 1299 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*Session).muxFrameToLink(0xc420813480, 0xc4204eca80, 0xa51aa0, 0xc4201945a0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:763 +0x135
github.com/devigned/testhub/vendor/pack.ag/amqp.(*Session).mux(0xc420813480, 0xc42045ab90)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:575 +0x40d
created by github.com/devigned/testhub/vendor/pack.ag/amqp.(*Client).NewSession
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:154 +0x589

goroutine 2716 [select, 1299 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*link).muxDetach(0xc4204eca80)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:1310 +0x19f
github.com/devigned/testhub/vendor/pack.ag/amqp.(*link).mux(0xc4204eca80)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:1016 +0x5ff
created by github.com/devigned/testhub/vendor/pack.ag/amqp.attachLink
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:937 +0x6f2

goroutine 2598 [select, 1336 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*conn).mux(0xc4201a85a0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/conn.go:368 +0xde5
created by github.com/devigned/testhub/vendor/pack.ag/amqp.(*conn).start
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/conn.go:260 +0xde

goroutine 843 [select, 2434 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*Session).muxFrameToLink(0xc420859100, 0xc4204ec180, 0xa51aa0, 0xc4202020c0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:763 +0x135
github.com/devigned/testhub/vendor/pack.ag/amqp.(*Session).mux(0xc420859100, 0xc4203106e0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:575 +0x40d
created by github.com/devigned/testhub/vendor/pack.ag/amqp.(*Client).NewSession
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:154 +0x589

goroutine 831 [select, 2434 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*conn).mux(0xc4200ba5a0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/conn.go:368 +0xde5
created by github.com/devigned/testhub/vendor/pack.ag/amqp.(*conn).start
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/conn.go:260 +0xde

goroutine 844 [select, 2434 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*link).muxDetach(0xc4204ec180)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:1310 +0x19f
github.com/devigned/testhub/vendor/pack.ag/amqp.(*link).mux(0xc4204ec180)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:996 +0x7a6
created by github.com/devigned/testhub/vendor/pack.ag/amqp.attachLink
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:937 +0x6f2

goroutine 829 [select, 2434 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*conn).connReader(0xc4200ba5a0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/conn.go:529 +0x32c
created by github.com/devigned/testhub/vendor/pack.ag/amqp.(*conn).start
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/conn.go:245 +0x43

goroutine 2681 [select, 1299 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*conn).mux(0xc4200bb0e0)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/conn.go:368 +0xde5
created by github.com/devigned/testhub/vendor/pack.ag/amqp.(*conn).start
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/conn.go:260 +0xde

goroutine 2626 [select, 1336 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*link).muxDetach(0xc420662600)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:1310 +0x19f
github.com/devigned/testhub/vendor/pack.ag/amqp.(*link).mux(0xc420662600)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:996 +0x7a6
created by github.com/devigned/testhub/vendor/pack.ag/amqp.attachLink
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:937 +0x6f2

goroutine 2614 [select, 1336 minutes]:
github.com/devigned/testhub/vendor/pack.ag/amqp.(*Session).muxFrameToLink(0xc420b2d500, 0xc420662600, 0xa51aa0, 0xc4200ce390)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:763 +0x135
github.com/devigned/testhub/vendor/pack.ag/amqp.(*Session).mux(0xc420b2d500, 0xc420310780)
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:575 +0x40d
created by github.com/devigned/testhub/vendor/pack.ag/amqp.(*Client).NewSession
	/go/src/github.com/devigned/testhub/vendor/pack.ag/amqp/client.go:154 +0x589

rax    0xca
rbx    0xd3b400
rcx    0x459493
rdx    0x0
rdi    0xd3b548
rsi    0x0
rbp    0x7ffec754d510
rsp    0x7ffec754d4c8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc4205d4e40
r13    0x2
r14    0xc420089020
r15    0x1
rip    0x459491
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by vcabbage** [comment]
@devigned Alright to close this now that #120 is merged?

**Comment by devigned** [comment]
Yep. I'll do the honors.
